only supervise web worker and urgentworker proc types

diff --git a/lib/procfile-to-supervisord b/lib/procfile-to-supervisord
--- a/lib/procfile-to-supervisord
+++ b/lib/procfile-to-supervisord
@@ -57,18 +57,20 @@ do
     continue
   fi
 
-  NAME=${line%%:*}
-  COMMAND=${line#*: }
-  NUM_PROCS=1
+  case "$line" in
+    web|worker|urgentworker)
+      NAME=${line%%:*}
+      COMMAND=${line#*: }
+      NUM_PROCS=1
 
-  if [ -f "$SCALEFILE" ]; then
-    SCALE=$(grep "$NAME=" "$SCALEFILE")
-    NUM_PROCS=${SCALE#*=}
-    if [ ! "$NUM_PROCS" -ge 1 ]; then
-      echo "Invalid scale line for process $NAME: $SCALE" 1>&2
-      exit 1
-    fi
-  fi
+      if [ -f "$SCALEFILE" ]; then
+        SCALE=$(grep "$NAME=" "$SCALEFILE")
+        NUM_PROCS=${SCALE#*=}
+        if [ ! "$NUM_PROCS" -ge 1 ]; then
+          echo "Invalid scale line for process $NAME: $SCALE" 1>&2
+          exit 1
+        fi
+      fi
 
   # Add a blank line in between processes:
   echo ""
